# Generated by Django 4.0.3 on 2022-03-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0002_contact_socialmedia_alter_videopost_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageItems',
            new_name='ImageItem',
        ),
    ]
