# Generated by Django 4.0.3 on 2022-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0003_rename_imageitems_imageitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='places',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(max_length=13, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='place',
            name='average_check',
            field=models.CharField(max_length=10, verbose_name='Средний чек'),
        ),
        migrations.AlterField(
            model_name='place',
            name='contact',
            field=models.CharField(max_length=10, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='working_time',
            field=models.CharField(max_length=15, verbose_name='Рабочие часы'),
        ),
    ]
