# Generated by Django 4.0.3 on 2022-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0004_rename_places_imagepost_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='place',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='Контакты'),
        ),
    ]
