# Generated by Django 4.0.3 on 2022-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0006_imagepost_top_alter_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(verbose_name='Ссылка социальную сеть'),
        ),
    ]
