# Generated by Django 4.0.3 on 2022-03-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0007_alter_socialmedia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='contact',
            name='body',
            field=models.CharField(default='', max_length=150, verbose_name='Номер телефона или email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.URLField(default='', verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(verbose_name='Ссылка на социальную сеть'),
        ),
    ]
