# Generated by Django 4.0.3 on 2022-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0008_remove_contact_email_remove_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Актуальный видеоотчет'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='video',
            field=models.FileField(default='', upload_to='video/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Ссылка'),
        ),
    ]
