# Generated by Django 4.0.3 on 2022-03-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0010_alter_videopost_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopost',
            old_name='video',
            new_name='url',
        ),
    ]
