# Generated by Django 4.0.3 on 2022-03-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0011_rename_video_videopost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='slug',
            field=models.SlugField(default=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
