# Generated by Django 4.0.3 on 2022-03-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0012_videopost_slug_alter_imagepost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Топ заведение'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image_posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='kipish.imagepost'),
        ),
    ]
