# Generated by Django 4.0.3 on 2022-03-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0013_place_top_alter_imageitem_image_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='count_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videopost',
            name='count_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CountViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesId', models.CharField(db_index=True, max_length=150)),
                ('image_post_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipish.imagepost')),
                ('video_post_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipish.videopost')),
            ],
        ),
    ]
