# Generated by Django 4.0.3 on 2022-03-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0014_imagepost_count_views_videopost_count_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='count_views',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='count_views',
        ),
        migrations.DeleteModel(
            name='CountViews',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='count_views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='kipish.saveip'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='count_views',
            field=models.ManyToManyField(blank=True, related_name='video_post_views', to='kipish.saveip'),
        ),
    ]
