# Generated by Django 4.0.3 on 2022-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0015_saveip_remove_imagepost_count_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Социальная сеть')),
                ('link', models.URLField(verbose_name='Ссылка на социальную сеть')),
                ('icon', models.FileField(upload_to='img/icon/')),
            ],
        ),
        migrations.AddField(
            model_name='videopost',
            name='videographer',
            field=models.CharField(default='', max_length=100, verbose_name='Видеограф'),
        ),
    ]
