# Generated by Django 4.0.3 on 2022-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0016_socialmediashare_videopost_videographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='created_at',
            field=models.DateField(verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='created_at',
            field=models.DateField(verbose_name='Дата события'),
        ),
    ]
