# Generated by Django 4.0.3 on 2022-03-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipish', '0017_alter_imagepost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='videographer',
            field=models.CharField(max_length=100, verbose_name='Видеограф'),
        ),
    ]
